services:
  app:
    build:
      context: .
    image: urlshortener-app:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/urlshortener
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
      JPA_DDL_AUTO: update
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
    volumes:
      - postgres18-data:/var/lib/postgresql

  redis:
    image: redis:8-alpine

volumes:
  postgres18-data:
