spring.application.name=urlshortener
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/urlshortener}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:12345}

spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=${REDIS_URL:localhost}
spring.data.redis.port=${REDIS_PORT:6379}